### ISSUE TITLE
Broken copy

### ISSUE THREAD

**Issue by davidemoro** [j23d/kotti_link#2]
The following error occurs when you try to copy a link resource (or a folder that contains a link item)

```
copy = self.__class__()
[console ready]
>>> self.__class__
<class 'kotti_link.resources.Link'>
>>> 
TypeError: __init__() takes exactly 2 arguments (1 given)
```

The fix should be very simple, coming soon a PR.

**Comment by davidemoro** [comment]
I've made a PR, please merge and release if it sounds good for you.

**Comment by j23d** [comment]
Sounds good, version 0.1 is released on pypi.

**Comment by davidemoro** [comment]
Thank you @j23d !
